const strings = {
  LOGIN: 'L o g i n',
  SIGNUP1: "Don't have an account ? ",
  SIGNUP2: 'Sign up.',
  LOGIN1: 'Already have an account ? ',
  LOGIN2: 'Sign in.',
  REGISTER: 'R e g i s t e r',
  LOGOUT: 'Log Out',
  WELCOME_TO_LOGIN: 'Login',
  WELCOME_TO_REGISTER: 'Register',
  WELCOME_TITLE_APP: 'Co HyPe',
  UNAME_PLACEHOLDER: 'Username',
  EMAIL_PLACEHOLDER: 'Email',
  PASSWORD_PLACEHOLDER: 'Password',
  TRYAGAIN: 'Try Again',
  MODALMSG: 'Sorry, something went wrong.',
  FONT: 'JosefinSans-Regular',
  FONT_BOLD: 'JosefinSans-Bold',
  FAVORITES: 'Favorites',
  ALL: 'Webtoons',
  CHECKIN: 'Checkin',
  ROOM: 'Room',
  CUSTOMER: 'Customer',
  SETTING: 'Settings',
  TRYAGAIN: 'Try Again',
  FAVWARN: "You don't have any favorites yet.",
  LOADING: 'Loading, please wait ..',
  IMAGE1_URL: 'dummy',
  IMAGE2_URL: 'dummy',
  IMAGE3_URL: 'dummy',
  IMAGE4_URL: 'dummy',
  IMAGE5_URL: 'dummy',
  IMAGE6_URL: 'dummy',
  CREATE_TOON_PAGE: 'My Toon Kingdom',
  TITLE: 'Title',
  EPISODE: 'Episode',
  NAME: 'Name',
  IMAGES: 'Images',
  ADD_EPISODE: '+ Episode',
  ADD_IMAGE: '+ Image',
  DELETE: 'Delete',
  SEARCH: 'Search here ..',
  TYPE: 'Type here ..',
  LIKE: ' Favorite(s)',
  TIMEOUT: 'Request Timeout',
  CANCEL: 'Cancel',
  SUBMIT: 'Submit',
  ROOMCFG: 'Room',
  CUSTOMERCFG: 'Customer',
  CHKINCFG: 'Checkin',
  RNAME: 'Room Name',
  CNAME: 'Customer Name',
  DURATION: 'Duration (minutes)',
  DURATION2: 'Duration Left (minutes)',
  INPUT_NAME: 'Name',
  INPUT_ID_NUM: 'ID Number',
  INPUT_PHONE_NUM: 'Phone Number',
};

export default strings;
